version: '3.8'

services:
  db:
    image: mariadb:10.11
    container_name: telysta_db
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - telysta_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./telystaback
    container_name: telysta_backend
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=3306
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - telysta_network
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - static_volume:/app/staticfiles
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8000 --workers 4 telystaback.wsgi:application"

  frontend:
    build: ./telystafront
    container_name: telysta_frontend
    ports:
      - "80:80"
    networks:
      - telysta_network
    environment:
      - VUE_APP_API_URL=${VUE_APP_API_URL}
    depends_on:
      - backend

volumes:
  db_data:
  static_volume:

networks:
  telysta_network:
    driver: bridge