version: '3.8'
name: telsytaweb

services:
  redis:
    image: "redis"
    container_name:  "redis"
    restart:  always
    healthcheck:
      test: ["CMD", "redis-cli","--raw","incr","ping"]
    volumes:
      - ./volumes/redis:/data
    networks:
      - telsytaweb
  db:
    image: "mysql"
    container_name: "db"
    restart: always
    env_file: .env
    environment: 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ALLOW_EMPTY_PASSWORD: ${DB_ALLOW_EMPTY_PASSWORD}
      MYSQL_DB_USER: ${DB_USER}
      MYSQL_DB_PASSWORD: ${DB_PASSWORD}
      MYSQL_DB_PORT: ${DB_PORT}
      TZ: ${TZ}
    command:
      --character-set-server=UTF8MB4
      --max_connections=1000
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
    volumes:
      - ./volumes/db/data:var/lib/mysql
    networks:
      - telsytaweb
    depends_on:
      redis:
        condition: service_healthy
  telystafront:
    build: ./telystafront
    container_name: "telystafront"
    restart: always
    ports: 
      - "80:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1"]
    networks:
      - telsytaweb
  telystaback:
    build: ./telystaback
    restart: always
    container_name: "telystaback"
    volumes:
      - .volumes/telystaback/sock:/data/sock
    networks:
      - telsytaweb
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
networks:
  telsytaweb:
    driver: "bridge"